### ISSUE TITLE
Filename /  path with space in LocalScheduler not working

### ISSUE THREAD

**Issue by dosomder** [sherpa-ai/sherpa#18]
The scheduler splits the command with spaces: https://github.com/LarsHH/sherpa/blob/master/sherpa/schedulers.py#L110

This means any file name / file path with space will not work. This should either be changed or mentioned in the docs.

**Comment by LarsHH** [comment]
Hi @dosomder !

Apologies for the slow reply. Good point.

It looks like this can be changed relatively easily. `_Runner` creates the command by joining `python` and `filename`. Then for `LocalScheduler` it gets split up again later. So there is some redundancy.

It seems to make sense to just pass a list with command components (i.e. ['python', filename]) to the scheduler. Then let the scheduler join it together or not, depending on what format is needed.

This slightly changes the interface of the `Scheduler.submit_job()` method, but since it is not really user facing I think that's okay.

Let me know if you have any more comments.

Best,
Lars

**Comment by LarsHH** [comment]
Resolved: https://github.com/sherpa-ai/sherpa/pull/20/commits/99de04f2a50ebe4d718e48a12bed59e070873a8d
